### ISSUE TITLE
[Enhancement] Add Contributors Table and Related DB

### ISSUE THREAD

**Issue by igorho2000** [tpe-doit/Taipei-City-Dashboard#151]
> Please submit all issues in English.

> This repository is still under internal development. All outside issues will be closed immediately.

## ⚠️⚠️Notice⚠️⚠️

For Taipei Codefest competitors, this issue is now assigned to another external contributor and as such is no longer a valid issue for the competition.

## Type

- [x] Application Functionalities
- [ ] New Chart Type
- [ ] New Map Type
- [ ] Other

## Please describe your feature request

Contributors are currently stored in a JSON file on the front end. Move the contributor info into a table in the DB and create add, get, modify, and delete APIs.

Use GitHub profile photos or other public sources instead of storing them locally on the front end. Also, add an admin page to utilize the above features.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by hsuanchi** [comment]
Hello @igorho2000,

I am interested in this ticket issue and want to contribute to the project. I hope to be assigned this task please 🙏🏻

**Comment by igorho2000** [comment]
Hi,

No problem. However as the main branch is currently reserved for the upcoming hackathon, please fork from the maintenance branch and pull request back to the maintenance branch instead of main. Thanks.

Deadline of completion: 5/9 (5/10 code review at the latest)
