### ISSUE TITLE
Demo Data Insertion Failure

### ISSUE THREAD

**Issue by ronchen820** [tpe-doit/Taipei-City-Dashboard#154]
After I clone the project and fill the necessary variables, when I try to initialize the frontend and backend environments, there is an error occured. When it tries to import "db-sample-data", it shows "error executing SQL file: error executing psql command: exit status 1".
![step2_error](https://github.com/tpe-doit/Taipei-City-Dashboard/assets/127047900/dd9775fa-4ee5-42c8-8781-f4a6793cb218)

**Comment by igorho2000** [comment]
Hi Ron, 

Thanks for notifying us of this issue. Two variables are missing from the .env.template file. 

```
DASHBOARD_SAMPLE_FILE=dashboard-demo.sql
MANAGER_SAMPLE_FILE=dashboardmanager-demo.sql
```

Kindly fill in your .env file with the above values and restart the setup process. Please also remember to delete /docker/db-data before reinitializing the databases.

If you have any other issues, please comment below or reference our documentation or tutorial.

We apologize for the issue. Thank you for using Taipei City Dashboard.

Sincerely,
Igor
